# Site settings
title: /users/null
email: gollum@f-m.fm
description: "quickbeam's notes"
url: "https://quickbeam.github.io"

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-minimal
