# Site settings
title: N1GMM Explorations
email: gollum@f-m.fm
description: "Things RF"
url: "https://quickbeam.github.io"

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-minimal
